CONFIG_GPIO=y
CONFIG_LOG=y

CONFIG_LED_STRIP=y

# Choose ONE backend that matches your compatible string above:
CONFIG_WS2812_STRIP_SPI=y   # Use if compatible = "worldsemi,ws2812-spi"
# CONFIG_WS2812_STRIP_GPIO=y

